project(ourokore_tests LANGUAGES CXX)

include_directories("../include")

add_executable(basic_tests basic_tests.cpp)
target_link_libraries(basic_tests ourokore_core)

add_executable(serialization_tests serialization_tests.cpp)
target_link_libraries(serialization_tests ourokore_core)

add_executable(base_sync_tests base_sync_tests.cpp)
target_link_libraries(base_sync_tests ourokore_base)

add_executable(base_threadpool_tests base_threadpool_tests.cpp)
target_link_libraries(base_threadpool_tests ourokore_base)

add_executable(ouro_lru_dehydrator_tests ouro_lru_dehydrator_tests.cpp)
target_link_libraries(ouro_lru_dehydrator_tests ourokore_core ourokore_base)

add_executable(core_async_tests core_async_tests.cpp)
target_link_libraries(core_async_tests ourokore_core ourokore_base)

add_executable(cycle_collector_tests cycle_collector_tests.cpp)
target_link_libraries(cycle_collector_tests ourokore_core ourokore_base)

add_executable(boundary_tests boundary_tests.cpp)
target_link_libraries(boundary_tests ourokore_core ourokore_base)

add_executable(plugin_isolation_tests plugin_isolation_tests.cpp)
target_link_libraries(plugin_isolation_tests ourokore_core ourokore_base)

add_library(test_plugin_dll MODULE test_plugin_dll.cpp)
set_target_properties(test_plugin_dll PROPERTIES 
    PREFIX ""
    LIBRARY_OUTPUT_DIRECTORY ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}
)

add_executable(base_dynamic_library_tests base_dynamic_library_tests.cpp)
target_link_libraries(base_dynamic_library_tests ourokore_base)
add_dependencies(base_dynamic_library_tests test_plugin_dll)
add_dependencies(boundary_tests test_plugin_dll)

add_executable(type_system_tests type_system_tests.cpp)
target_link_libraries(type_system_tests ourokore_core ourokore_base)

add_executable(base_hash_tests base_hash_tests.cpp)
target_link_libraries(base_hash_tests ourokore_base)

add_executable(test_proxy test_proxy.cpp)
target_link_libraries(test_proxy ourokore_core ourokore_base)

